BEGIN TRANSACTION;
CREATE TABLE IngredientsTable (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, category TEXT);
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (1,'Onion','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (2,'Potato','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (3,'Tomato','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (4,'Artichoke','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (5,'Asparagus','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (6,'Beetroot','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (7,'Bell pepper','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (8,'Broccoli','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (9,'Brussel sprout','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (10,'Cabbage','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (11,'Carrot','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (12,'Cauliflower','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (13,'Celery','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (14,'Cucumber','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (15,'Eggplant','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (16,'Green bean','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (17,'Lettuce','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (18,'Mushroom','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (19,'Pea','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (20,'Pumpkin','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (21,'Radish','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (22,'Zucchini','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (23,'Leek','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (24,'Brussel sprouts','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (25,'Chili','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (26,'Spring onions','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (27,'Corn','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (28,'Aubergine','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (29,'Arugula','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (30,'Spinach','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (31,'Shallot','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (32,'Garlic','Vegetable');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (33,'Orange','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (34,'Mandarin','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (35,'Grapefruit','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (36,'Lime','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (37,'Lemon','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (38,'Kiwi','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (39,'Pineapple','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (40,'Pomegranate','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (41,'Avocado','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (42,'Pomelo','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (43,'Coconut','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (44,'Melon','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (45,'Banana','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (46,'Pear','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (47,'Peach','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (48,'Plum','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (49,'Quince','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (50,'Apricot','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (51,'Watermelon','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (52,'Cherry','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (53,'Blueberry','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (54,'Apple','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (55,'Strawberry','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (56,'Grape','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (57,'Fig','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (58,'Pitaya','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (59,'Papaya','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (60,'Raspberry','Fruit');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (61,'Basil','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (62,'Dill','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (63,'Marjoram','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (64,'Thyme','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (65,'Chives','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (66,'Mint','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (67,'Oregano','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (68,'Rosemary','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (69,'Parsley','Herb');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (70,'Pepper','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (71,'Cardamon','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (72,'Star anise','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (73,'Coriander','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (74,'Clove','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (75,'Nutmeg','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (76,'Cumin','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (77,'Cinnamon','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (78,'Ginger','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (80,'Walnuts','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (81,'Pistacios','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (82,'Pine nuts','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (83,'Pecans','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (84,'Peanuts','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (85,'Hazelnuts','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (86,'Cashews','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (87,'Almonds','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (88,'Brazil nuts','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (89,'Macadamias','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (90,'Flax','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (91,'Sunflower','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (92,'Hemp','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (93,'Pumpkin','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (94,'Corn','Nuts_Seeds');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (95,'Milk','Dairy');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (96,'Cream','Dairy');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (97,'Yogurt','Dairy');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (98,'Ice cream','Dairy');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (99,'Sour cream','Dairy');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (100,'Cheese','Dairy');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (101,'Butter','Dairy');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (102,'Cheerios','Cereal');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (103,'Corn flakes','Cereal');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (104,'Honey oats','Cereal');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (105,'Bran','Cereal');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (106,'Crispy rice','Cereal');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (107,'Oatmeal','Cereal');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (108,'Coconut Oil','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (109,'Lard','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (110,'Olive Oil','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (111,'Peanut Oil','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (112,'Vegetable Oil','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (113,'Corn Oil','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (114,'Soybean Oil','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (115,'Sunflower Oil','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (116,'Canola Oil','Oil');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (117,'Salmon','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (118,'Crab','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (119,'Tuna','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (120,'Pollock','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (121,'Shrimp','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (122,'Cod','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (123,'Pangasius','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (124,'Catfish','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (125,'Clams','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (126,'Tilapia','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (127,'Oysters','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (128,'Mackerel','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (129,'Flounder','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (130,'Herring','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (131,'Mussels','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (132,'Sardines','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (133,'Sole','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (134,'Crab','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (135,'Haddock','Seafood');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (137,'Duck','Poultry');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (138,'Turkey','Poultry');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (139,'Geese','Poultry');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (140,'Chiken','Poultry');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (141,'Lamb','Meat');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (142,'Pork','Meat');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (143,'Beef','Meat');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (144,'Veal','Meat');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (145,'Eggs','Other');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (146,'Pasta','Other');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (147,'Flour','Other');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (148,'Rice','Other');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (149,'Paprika','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (150,'Curry','Spice');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (151,'Noodles','Other');
INSERT INTO `IngredientsTable` (_id,name,category) VALUES (152,'Sugar','Spice');
COMMIT;
